### ISSUE TITLE
README - Deployment - Step 1

### ISSUE THREAD

**Issue by montgolfiere** [Alfresco/alfresco-infrastructure-deployment#4]
Deployment - step 1 - Install the nginx-ingress-controller

> helm install stable/nginx-ingress \
> --version 0.8.11 \
> --namespace $DESIREDNAMESPACE

Error: failed to download "stable/nginx-ingress"

Seemed to work ok with 0.8.0 to 0.8.9. Apparently fails for any version >= 0.8.10 (at least a few that I tried) ?!

Using helm v2.8.1 on Mac.

$ helm repo list
NAME  	URL                                             
stable	https://kubernetes-charts.storage.googleapis.com
local 	http://127.0.0.1:8879/charts

**Comment by montgolfiere** [comment]
FYI: I eventually resolved it by doing:

$ helm repo update

Maybe we could add this extra step to the README to save others some time ?

**Comment by sergiuv2020** [comment]
Thank You Jan 🥇
